export const ORGANIZATION_TYPES = [
  'COMPANY',
  'NON_PROFIT',
  'GOVERNMENT',
  'EDUCATIONAL',
  'STARTUP',
  'ENTERPRISE'
];

export const ORGANIZATION_INDUSTRIES = [
  'TECHNOLOGY',
  'HEALTHCARE',
  'FINANCE',
  'EDUCATION',
  'RETAIL',
  'MANUFACTURING',
  'CONSTRUCTION',
  'REAL_ESTATE',
  'HOSPITALITY',
  'TRANSPORTATION',
  'MEDIA',
  'ENERGY',
  'AGRICULTURE',
  'OTHER'
];

export const ORGANIZATION_STATUS = [
  'ACTIVE',
  'INACTIVE',
  'SUSPENDED',
  'PENDING_VERIFICATION'
];

export const JOB_CATEGORIES = [
  'TECHNOLOGY',
  'SALES',
  'MARKETING',
  'FINANCE',
  'HR',
  'OPERATIONS',
  'LEGAL',
  'HEALTHCARE',
  'EDUCATION',
  'CONSTRUCTION',
  'HOSPITALITY',
  'RETAIL',
  'MANUFACTURING',
  'OTHER'
];

export const EMPLOYMENT_TYPES = [
  'FULL_TIME',
  'PART_TIME',
  'CONTRACT',
  'TEMPORARY',
  'INTERNSHIP',
  'FREELANCE'
];

export const EXPERIENCE_LEVELS = [
  'ENTRY_LEVEL',
  'JUNIOR',
  'MID_LEVEL',
  'SENIOR',
  'LEAD',
  'MANAGER',
  'DIRECTOR',
  'EXECUTIVE'
];

export const OPPORTUNITY_TYPES = [
  'INTERNSHIP',
  'SCHOLARSHIP',
  'GRANT',
  'FELLOWSHIP',
  'TRAINING',
  'COMPETITION',
  'EVENT',
  'VOLUNTEER',
  'OTHER'
];
